from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from io import BytesIO
from typing import List
from app.models.presentation import SlideContent
import requests

# Colors
NAVY = RGBColor(0, 31, 63)
AMBER = RGBColor(245, 158, 11)
WHITE = RGBColor(255, 255, 255)
GRAY = RGBColor(200, 200, 200)

def create_presentation(topic: str, slides_content: List[SlideContent]) -> BytesIO:
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    
    # Apply Theme to Title Slide
    _apply_background(slide)
    
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = topic
    subtitle.text = "Generated by Somlearn AI"
    
    _style_text(title, color=AMBER, size=Pt(54), bold=True)
    _style_text(subtitle, color=GRAY, size=Pt(24))

    # Content Slides
    for slide_data in slides_content:
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        _apply_background(slide)
        
        # Title
        title_shape = slide.shapes.title
        title_shape.text = slide_data.title
        _style_text(title_shape, color=AMBER, size=Pt(40), bold=True)
        
        # Content
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.clear()  # Clear default empty paragraph
        
        for point in slide_data.content:
            p = tf.add_paragraph()
            p.text = point
            p.space_after = Pt(14)
            _style_text(p, color=WHITE, size=Pt(20))

        # Add Image if available (Placeholder or URL)
        # Note: In a real app, we need to download the image from URL.
        # Here we will skip actual downloading to avoid network errors in this environment
        # or use a placeholder shape if url is 'mock'
        if slide_data.image_url:
            # Placeholder for image area
            left = Inches(5.5)
            top = Inches(2)
            width = Inches(4)
            height = Inches(4)
            
            # shape = slide.shapes.add_picture(image_stream, left, top, width, height)
            # Drawing a rectangle instead for safety
            shape = slide.shapes.add_shape(
                1, # MSO_SHAPE.RECTANGLE
                left, top, width, height
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = RGBColor(20, 40, 80)
            shape.line.color.rgb = AMBER

    # Save to buffer
    output = BytesIO()
    prs.save(output)
    output.seek(0)
    return output

def _apply_background(slide):
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = NAVY

def _style_text(text_obj, color, size, bold=False):
    # text_obj can be a shape (title) or a paragraph
    if hasattr(text_obj, 'text_frame'):
        for p in text_obj.text_frame.paragraphs:
            _style_paragraph(p, color, size, bold)
    else:
        # It's a paragraph
        _style_paragraph(text_obj, color, size, bold)

def _style_paragraph(paragraph, color, size, bold):
    paragraph.font.color.rgb = color
    paragraph.font.size = size
    paragraph.font.bold = bold
    paragraph.font.name = 'Arial'
